# Log Transformation

In [11]:
from sklearn.preprocessing import PowerTransformer
import numpy as np
from scipy.stats import skew
import matplotlib.pyplot as plt

X_train = [[10], [20], [30], [40], [60], [100], [200], [500], [1000], [5000]]
X_test  = [[50], [80], [150], [300], [800]]

X_train_log = np.log1p(X_train)
X_test_log = np.log1p(X_test)
print("Before Log Transformation :")
print(X_train)

print("After Log Transformation :")
print(X_train_log)

print("Before Log Transformation :")
print(X_test)

print("After Log Transformation :")
print(X_test_log)



Before Log Transformation :
[[10], [20], [30], [40], [60], [100], [200], [500], [1000], [5000]]
After Log Transformation :
[[2.39789527]
 [3.04452244]
 [3.4339872 ]
 [3.71357207]
 [4.11087386]
 [4.61512052]
 [5.30330491]
 [6.2166061 ]
 [6.90875478]
 [8.51739317]]
Before Log Transformation :
[[50], [80], [150], [300], [800]]
After Log Transformation :
[[3.93182563]
 [4.39444915]
 [5.01727984]
 [5.70711026]
 [6.68586095]]


# Box-Cox Transformation

In [14]:
from sklearn.preprocessing import PowerTransformer
import numpy as np
import matplotlib.pyplot as plt

X_train = [[10], [20], [30], [40], [60], [100], [200], [500], [1000], [5000]]
X_test  = [[50], [80], [150], [300], [800]]

boxcox = PowerTransformer(method="box-cox")

X_train_boxcox = boxcox.fit_transform(X_train)
X_test_boxcox = boxcox.transform(X_test)

print("Before Log Transformation :")
print(X_train)

print("After Log Transformation :")
print(X_train_boxcox)

print("Before Log Transformation :")
print(X_test)

print("After Log Transformation :")
print(X_test_boxcox)



Before Log Transformation :
[[10], [20], [30], [40], [60], [100], [200], [500], [1000], [5000]]
After Log Transformation :
[[-1.64246628]
 [-1.05638425]
 [-0.74614398]
 [-0.53943831]
 [-0.26579498]
 [ 0.05154883]
 [ 0.43779946]
 [ 0.87937206]
 [ 1.16797003]
 [ 1.71353742]]
Before Log Transformation :
[[50], [80], [150], [300], [800]]
After Log Transformation :
[[-0.38635877]
 [-0.08347296]
 [ 0.28335353]
 [ 0.64225974]
 [ 1.07898547]]


In [17]:
from scipy.stats import skew

print("Original:", skew(X_train))
print("Log:", skew(X_train_log.flatten()))
print("Box-Cox:", skew(X_train_boxcox.flatten()))

Original: [2.47909434]
Log: 0.6309079724539091
Box-Cox: 0.11877654931057866
